### ISSUE TITLE
owen frie

### ISSUE THREAD

**Issue by xseano** [packetflooder/POLLauncherCode#1]
owen frie
+1 (972) 838-8856

¯\_(ツ)_/¯ if you dont want anything to happen, take my code down before i file a DMCA

**Comment by packetflooder** [comment]
Not your code, its altis.
Why call me out for "stealing code" When yours is stolen as well?

**Comment by xseano** [comment]
i wrote that code for altis LOL

**Comment by ethanlindley** [comment]
i don't think you know who initially wrote the code for this launcher at altis..

(both of which currently are staff at POL)

**Comment by packetflooder** [comment]
also, electron? i can just unpack the asar.  You all are complete skids.

**Comment by ethanlindley** [comment]
hmmmmmmmmmmmmmmmmmmmmmmmmmm

**Comment by Bob693** [comment]
Wow so professional releasing my info?

**Comment by xseano** [comment]
rip owen frie

**Comment by Bob693** [comment]
Perfect example of POL's unprofessionalism! Thanks for proving my points guys!

**Comment by Bob693** [comment]
I'm not going to be a skid and a literal douchebag leaking your info sean. Instead i'm going to expose you and your entire team! Leaking my info is the lowest of the low. Have fun!

You've ruined what could be a great thing. Bringing back 2008 POTCO. But you blew it!

**Comment by Bob693** [comment]
"if you dont want anything to happen, take my code down before i file a DMCA" Thanks for the threats! However you have no legal right to legally take this repo down bud!
